version: "3.8"

services:
  server:
    args:
      - IMAGE_TAG=${IMAGE_TAG}
    image: gcr.io/banded-meridian-435911-g6/youtube-backend:${IMAGE_TAG}
    ports:
      - "8800:8800"
    environment:
      - MONGO=${MONGO}
      - JWT=${JWT}
    restart: unless-stopped

  client:
    args:
      - IMAGE_TAG=${IMAGE_TAG}
    image: gcr.io/banded-meridian-435911-g6/youtube-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
    environment:
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
    restart: unless-stopped
    depends_on:
      - server

volumes:
  mydata:
