version: "3.8"

services:
  server:
    image: gcr.io/banded-meridian-435911-g6/youtube-backend:latest
    ports:
      - "8800:8800"
    environment:
      - MONGO=${MONGO}
      - JWT=${JWT}
    restart: unless-stopped

  client:
    image: gcr.io/banded-meridian-435911-g6/youtube-frontend:latest
    ports:
      - "80:80"
    environment:
      - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
    restart: unless-stopped
    depends_on:
      - server

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
      - certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"

volumes:
  certbot-etc:
  certbot-var:
