version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=${IMAGE_TAG}
    image: youtube-backend:${IMAGE_TAG}

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - IMAGE_TAG=${IMAGE_TAG}
    image: youtube-frontend:${IMAGE_TAG}
