name: Build and Deploy to Google Compute Engine

on:
  push:
    # Turning off staging for now...
    # branches:
    #   - master
    tags:
      - v\d+\.\d+\.\d+

env:
  PROJECT_ID: banded-meridian-435911-g6

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set ENV
        run: |-
          if [ ${GITHUB_REF##*/} = "main" ]; then
            echo "ENV=staging" >> $GITHUB_ENV
          else 
            echo "ENV=prod" >> $GITHUB_ENV
          fi

      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          workload_identity_provider: "projects/376749813573/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "githubactions@banded-meridian-435911-g6.iam.gserviceaccount.com"
          version: "290.0.1"

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker
      - name: Setup Docker Compose
        run: |-
          make install-docker
          make install-docker-compose

      # Build the Docker image
      - name: Build
        run: |-
          make build

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          make push

      - name: Deploy
        run: |-
          make deploy
